language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-9.0.5.0
jdk:
  - oraclejdk8
script: bundle exec rspec --color --format=documentation
addons:
  code_climate:
    repo_token: &codeclimate_token 6d4a51b47839a35d44ba7a899bd12e7cb4c519664cf2508724f8765210493ba2
env:
  global:
    - CODECLIMATE_REPO_TOKEN: *codeclimate_token
    - CI: true
branches:
  only:
    - master
    - /^staging.*$/
before_install:
  - gem update --system
