language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.5
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-9.0.5.0
jdk:
  - oraclejdk8
  - openjdk8
matrix:
  exclude:
    - rvm: 2.1.5
      jdk: openjdk8
    - rvm: 2.1.5
      jdk: oraclejdk8
    - rvm: 2.1.9
      jdk: openjdk8
    - rvm: 2.1.9
      jdk: oraclejdk8
    - rvm: 2.2.5
      jdk: openjdk8
    - rvm: 2.2.5
      jdk: oraclejdk8
    - rvm: 2.3.1
      jdk: openjdk8
    - rvm: 2.3.1
      jdk: oraclejdk8
    - rvm: ruby-head
      jdk: openjdk8
    - rvm: ruby-head
      jdk: oraclejdk8
script: bundle exec rspec --color --format=documentation
addons:
  code_climate:
    repo_token: &codeclimate_token 6d4a51b47839a35d44ba7a899bd12e7cb4c519664cf2508724f8765210493ba2
env:
  global:
    - CODECLIMATE_REPO_TOKEN: *codeclimate_token
    - CI: true
branches:
  only:
    - master
    - /^staging.*$/
